http.host=0.0.0.0
http.port=8085

db.host=ec2-3-21-224-150.us-east-2.compute.amazonaws.com
db.port=3306
db.user=mule
db.database=training

circuitBreaker.failureThreshold=3
circuitBreaker.resetTimeoutMs=120000

notification.api.protocol=HTTPS
notification.api.host=notify.example.com
notification.api.port=443
notification.api.basePath=/api/v1

notification.email.enabled=false
notification.email.host=smtp.example.com
notification.email.port=587
notification.email.user=no-reply@example.com
notification.email.from=no-reply@example.com
notification.email.to=ops@example.com

ops.heartbeat.enabled=true
ops.heartbeat.frequencySeconds=300

external.logging.enabled=false
external.logging.protocol=HTTPS
external.logging.host=logs.example.com
external.logging.port=443
external.logging.basePath=/ingest/mulesoft

api.autodiscovery.id=20817134
